print("vamos a realizar una equacion de tercer grado, digame la primera cifra: ")
numero1=input()
primera=int(numero1)
print("digame la segunda cifra: ")
numero2=input()
segunda=int(numero2)
print("digame una tercera cifra: ")
numero3=input()
tercera=int(numero3)
print("digame una cuarta cifra: ")
numero4=input()
cuarta=int(numero4)
print("¿cual es el valor de x?")
x=input()
x=int(x)
print("la solucion a esta equacion es: ", primera + segunda * x + tercera * x * x + cuarta * x * x * x * x,)