print("¿cuantos de sabor de cola se ha vendido?")
cola=input()
producto1=int(cola)
print("¿cuantos de sabor de naranja se ha vendido?")
naranja=input()
producto2=int(naranja)
print("¿cunatos de sabor de limon?")
limon=input()
producto3=int(limon)
print("-----------------------------------------------------------------------")
print("Producto ventas precio total")
print("-----------------------------------------------------------------------")
print("Cola", producto1 ,"0,17", producto1*0.17)
print("")
print("naranja", producto2 ,"0,20", producto2*0.20)
print("")
print("limon", producto3 ,"0,19", producto3*0.19)
print("-----------------------------------------------------------------------")
print("TOTAL", producto1 * 0.18 + producto2 * 0.20 + producto3*0.19,)