
print("primer numero")
primer=input()
numero1=int(primer)
print("segundo numero")
segundo=input()
numero2=int(segundo)
print("la suma es ", numero1 + numero2 ,)
print("la resta es", numero1 - numero2 ,)
print("la multiplicación es", numero1 * numero2 ,)
print("la división es", numero1 / numero2 ,)
print("el modulo es", numero1 % numero2,)
print("Introduce la base del rectangulo")
base=input()
base=int(base)
print("introduce la altura del rectangulo")
altura=input()
altura=int(altura)
print("el area es", base * altura ,"m2")