adn=input("Dime cual es tu secuencia de ADN: ")
print("numero de A: ",adn.count("a") or adn.count("A"))
print("numero de C: ",adn.count("c") or adn.count("C"))
print("numero de G: ",adn.count("g") or adn.count("G"))
print("numero de T: ",adn.count("t") or adn.count("T"))