import math
print("Bienvenido al calculador de equaciones,")
print("dime el primer numero: ")
primer=input()
a=int(primer)
print("dime el segundo numero: ")
segundo=input()
b=int(segundo)
print("dime el tercer numero: ")
tercer=input()
c=int(tercer)
print("el resultado positivo es: " , (-(b)+math.sqrt(b**2-4*a*c))/2*a)
print("el resultado negativo es: " , (-(b)-math.sqrt(b**2-4*a*c))/2*a)