print("Bienvenido al calculador de equaciones,")
print("dime el primer numero: ")
primer=input()
numero1=int(primer)
print("dime el segundo numero: ")
segundo=input()
numero2=int(segundo)
print("dime el tercer numero: ")
tercer=input()
numero3=int(tercer)
print("¿cuanto vale X?")
x=input()
x=int(x)
print(segundo**2)
import math
math.sqrt(9)
raiz=math.sqrt
print(raiz)